branches:
  - name: main
    protection:
      enforce_admins: true
      required_linear_history: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_status_checks:
        contexts: []
        strict: true
      restrictions: null

repository:
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  default_branch: main
  delete_branch_on_merge: true
  has_issues: false
  has_projects: false
  has_wiki: false
  private: false
